name: DevOps CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make test.sh executable
      run: chmod +x test.sh

    - name: Run test script
      run: ./test.sh
